@api = https://localhost:5001
@bookId = fe03919f-b708-491c-9d97-a8ea49a16968

### Create new book
POST {{api}}/api/books
content-type: application/json

{
    "title": "Domain-driven design",
    "author": "Eric J. Evans",
    "tags": ["new"],
    "cost": 500,
    "inventoryAmount": 20
}
### Get book
GET {{api}}/api/books/{{bookId}}

### Get books
GET {{api}}/api/books

### Add Tag
POST {{api}}/api/books/{{bookId}}/tag
content-type: application/json

{
    "tag": "super"
}

### Remove Tag
DELETE  {{api}}/api/books/{{bookId}}/tag
content-type: application/json

{
    "tag": "super"
}