@api = https://localhost:5001
@bookId = a064071c-6c57-42b8-b629-c3c1c6993ab1

### Create new book
POST {{api}}/api/books
content-type: application/json

{
    "title": "Super new book",
    "author": "Marian Bubak",
    "tags": ["new", "tag"],
    "cost": 500,
    "inventoryAmount": 20
}
### Get book
GET {{api}}/api/books/{{bookId}}


### Get books
GET {{api}}/api/books

### Add Tag
POST {{api}}/api/books/{{bookId}}/tag
content-type: application/json

{
    "tag": "super"
}